[package]
name = "autopiercam-regain-worker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "regain-device"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
regain-zwo.workspace = true
regain-transport.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_UI_Shell"] }

[build-dependencies]
embed-resource.workspace = true

[dev-dependencies]
regain-core.workspace = true
autopiercam = { path = "../autopiercam" }
autopiercam-camera = { path = "../autopiercam-camera", features = ["simulator"] }
autopiercam-core = { path = "../autopiercam-core" }
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
