[package]
name = "autopiercam"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
autopiercam-asi = { path = "../autopiercam-asi" }
autopiercam-core = { path = "../autopiercam-core" }
autopiercam-protocol = { path = "../autopiercam-protocol" }
clap.workspace = true
ctrlc.workspace = true
image.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ureq.workspace = true
